// Generated by mozaiks InfraScaffoldAgent. Edit after generation as needed.
/**
 * OIDC auth adapter for {{APP_SLUG}}.
 *
 * Supports two modes:
 *   - Mock mode (VITE_MOCK_MODE=true): always authenticated, no redirects.
 *   - OIDC mode (VITE_OIDC_AUTHORITY or VITE_OIDC_DISCOVERY_URL set): PKCE auth-code flow through OIDC discovery.
 *
 * Implements the authAdapter contract consumed by ChatUIProvider:
 *   getCurrentUser()             -> Promise<user | null>
 *   onAuthStateChange(callback)  -> () => void (unsubscribe)
 *   login()                      -> Promise<void> (initiates OIDC redirect)
 *   logout()                     -> Promise<void>
 *   getAccessToken()             -> string | null
 *   handleCallback()             -> Promise<{ returnPath: string }> (call from AuthCallbackPage)
 *
 * Template variables substituted at generation time:
 *   {{APP_SLUG}}            - app slug used in storage key prefix and error messages
 *   {{TOKEN_KEY_PREFIX}}    - sessionStorage key prefix (defaults to APP_SLUG)
 *   {{OIDC_CLIENT_ID}}      - OIDC client_id baked into the Vite bundle
 *   {{AUTH_DEFAULT_ROUTE}}  - safe post-login fallback route
 */

const TOKEN_KEY = '{{TOKEN_KEY_PREFIX}}_access_token';
const USER_KEY = '{{TOKEN_KEY_PREFIX}}_user';
const RETURN_KEY = '{{TOKEN_KEY_PREFIX}}_return_path';
const VERIFIER_KEY = '{{TOKEN_KEY_PREFIX}}_pkce_verifier';
const TRANSACTION_KEY = '{{TOKEN_KEY_PREFIX}}_oidc_transactions';
const TRANSACTION_TTL_MS = 15 * 60 * 1000;
const AUTH_EVENT = '{{TOKEN_KEY_PREFIX}}:auth:changed';
const DEFAULT_RETURN_PATH = '{{AUTH_DEFAULT_ROUTE}}';

function generateVerifier() {
  const array = new Uint8Array(96);
  window.crypto.getRandomValues(array);
  return btoa(String.fromCharCode(...array))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

async function generateChallenge(verifier) {
  const data = new TextEncoder().encode(verifier);
  const digest = await window.crypto.subtle.digest('SHA-256', data);
  return btoa(String.fromCharCode(...new Uint8Array(digest)))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

function parseJsonObject(raw) {
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

function pruneTransactions(transactions, now = Date.now()) {
  return Object.fromEntries(
    Object.entries(transactions).filter(([, transaction]) => {
      if (!transaction || typeof transaction !== 'object') return false;
      if (typeof transaction.verifier !== 'string' || !transaction.verifier) return false;
      const createdAt = Number(transaction.createdAt || 0);
      return createdAt > 0 && now - createdAt <= TRANSACTION_TTL_MS;
    }),
  );
}

function readTransactions() {
  return pruneTransactions(parseJsonObject(sessionStorage.getItem(TRANSACTION_KEY)));
}

function writeTransactions(transactions) {
  const pruned = pruneTransactions(transactions);
  if (Object.keys(pruned).length === 0) {
    sessionStorage.removeItem(TRANSACTION_KEY);
    return;
  }
  sessionStorage.setItem(TRANSACTION_KEY, JSON.stringify(pruned));
}

function safeReturnPath(value) {
  if (typeof value !== 'string') return DEFAULT_RETURN_PATH;
  if (!value.startsWith('/') || value.startsWith('//')) return DEFAULT_RETURN_PATH;
  return value;
}

function writeAuthTransaction(transaction) {
  const transactions = readTransactions();
  transactions[transaction.state] = transaction;
  writeTransactions(transactions);
}

function readAuthTransaction(state) {
  if (!state) return null;
  const transactions = readTransactions();
  const transaction = transactions[state];
  writeTransactions(transactions);
  return transaction || null;
}

function readLegacyTransaction() {
  const verifier = sessionStorage.getItem(VERIFIER_KEY);
  if (!verifier) return null;
  return {
    state: '',
    verifier,
    returnPath: safeReturnPath(sessionStorage.getItem(RETURN_KEY) || DEFAULT_RETURN_PATH),
    createdAt: Date.now(),
  };
}

function clearAuthTransaction(state = '') {
  if (state) {
    const transactions = readTransactions();
    delete transactions[state];
    writeTransactions(transactions);
  } else {
    sessionStorage.removeItem(TRANSACTION_KEY);
  }
  sessionStorage.removeItem(VERIFIER_KEY);
  sessionStorage.removeItem(RETURN_KEY);
}

function decodeJwtPayload(token) {
  try {
    const [, payload] = token.split('.');
    const padded = payload.replace(/-/g, '+').replace(/_/g, '/');
    return JSON.parse(atob(padded));
  } catch {
    return null;
  }
}

function isTokenExpired(token) {
  const payload = decodeJwtPayload(token);
  if (!payload?.exp) return false;
  return Date.now() / 1000 > payload.exp - 30;
}

function userFromPayload(payload) {
  if (!payload) return null;
  const sub = payload.sub || payload.user_id || payload.email;
  return {
    id: sub,
    user_id: sub,
    email: payload.email || null,
    name: payload.name || payload.preferred_username || payload.email || sub,
    firstName: payload.given_name || null,
    lastName: payload.family_name || null,
    roles: payload.realm_access?.roles || payload.roles || [],
  };
}

function createMockAdapter() {
  const mockUser = {
    id: 'dev-user',
    user_id: 'dev-user',
    email: 'dev@{{APP_SLUG}}.local',
    name: 'Developer',
    firstName: 'Dev',
    lastName: 'User',
    roles: ['admin', 'user'],
  };

  return {
    getCurrentUser: () => Promise.resolve(mockUser),
    onAuthStateChange: (callback) => {
      callback(mockUser);
      return () => {};
    },
    login: () => Promise.resolve(),
    logout: () => {
      window.location.href = '/';
      return Promise.resolve();
    },
    getAccessToken: () => 'dev-token',
    handleCallback: () => Promise.resolve({ returnPath: DEFAULT_RETURN_PATH }),
  };
}

function createOidcAdapter({ authority, discoveryUrl, clientId, redirectUri, scope }) {
  const listeners = new Set();
  let metadataPromise = null;

  function resolveDiscoveryUrl() {
    if (discoveryUrl) return discoveryUrl;
    const cleanAuthority = authority.replace(/\/$/, '');
    if (cleanAuthority.endsWith('/.well-known/openid-configuration')) {
      return cleanAuthority;
    }
    return `${cleanAuthority}/.well-known/openid-configuration`;
  }

  async function resolveMetadata() {
    if (!metadataPromise) {
      metadataPromise = fetch(resolveDiscoveryUrl(), {
        headers: { Accept: 'application/json' },
      }).then(async (res) => {
        if (!res.ok) {
          const body = await res.text().catch(() => '');
          throw new Error(`OIDC discovery failed: HTTP ${res.status} ${body}`.trim());
        }
        const metadata = await res.json();
        if (!metadata.authorization_endpoint || !metadata.token_endpoint) {
          throw new Error('OIDC discovery document is missing authorization_endpoint or token_endpoint');
        }
        return metadata;
      });
    }
    return metadataPromise;
  }

  function notify() {
    window.dispatchEvent(new CustomEvent(AUTH_EVENT));
  }

  function getStoredToken() {
    return sessionStorage.getItem(TOKEN_KEY);
  }

  function getStoredUser() {
    try {
      const raw = sessionStorage.getItem(USER_KEY);
      return raw ? JSON.parse(raw) : null;
    } catch {
      return null;
    }
  }

  function clearStoredUserSession() {
    sessionStorage.removeItem(TOKEN_KEY);
    sessionStorage.removeItem(USER_KEY);
  }

  function clearSession() {
    clearStoredUserSession();
    clearAuthTransaction();
  }

  return {
    getCurrentUser: async () => {
      const token = getStoredToken();
      if (!token || isTokenExpired(token)) {
        clearStoredUserSession();
        return null;
      }
      const stored = getStoredUser();
      if (stored) return stored;
      const payload = decodeJwtPayload(token);
      return userFromPayload(payload);
    },

    onAuthStateChange: (callback) => {
      const handler = async () => {
        const token = getStoredToken();
        if (token && !isTokenExpired(token)) {
          const user = getStoredUser() || userFromPayload(decodeJwtPayload(token));
          callback(user);
        } else {
          callback(null);
        }
      };
      listeners.add(handler);
      window.addEventListener(AUTH_EVENT, handler);
      handler();

      return () => {
        listeners.delete(handler);
        window.removeEventListener(AUTH_EVENT, handler);
      };
    },

    login: async () => {
      const metadata = await resolveMetadata();
      const returnPath = safeReturnPath(window.location.pathname + window.location.search);

      const verifier = generateVerifier();
      const challenge = await generateChallenge(verifier);
      const state = generateVerifier();
      writeAuthTransaction({
        state,
        verifier,
        returnPath,
        createdAt: Date.now(),
      });

      // Compatibility fallback for callbacks already in flight during a deploy.
      sessionStorage.setItem(VERIFIER_KEY, verifier);
      sessionStorage.setItem(RETURN_KEY, returnPath);

      const params = new URLSearchParams({
        client_id: clientId,
        redirect_uri: redirectUri,
        response_type: 'code',
        scope,
        code_challenge: challenge,
        code_challenge_method: 'S256',
        state,
      });

      window.location.href = `${metadata.authorization_endpoint}?${params.toString()}`;
    },

    logout: async () => {
      let metadata = null;
      try {
        metadata = await resolveMetadata();
      } catch {
        metadata = null;
      }
      const token = getStoredToken();
      clearSession();
      notify();

      if (!metadata?.end_session_endpoint) {
        window.location.href = '/login';
        return;
      }

      const params = new URLSearchParams({
        client_id: clientId,
        post_logout_redirect_uri: window.location.origin + '/login',
      });

      if (token) {
        params.set('id_token_hint', token);
      }

      window.location.href = `${metadata.end_session_endpoint}?${params.toString()}`;
    },

    getAccessToken: () => {
      const token = getStoredToken();
      return token && !isTokenExpired(token) ? token : null;
    },

    handleCallback: async () => {
      const metadata = await resolveMetadata();
      const params = new URLSearchParams(window.location.search);
      const code = params.get('code');
      if (!code) throw new Error('No authorization code in callback URL');

      const state = params.get('state') || '';
      const transaction = readAuthTransaction(state) || (!state ? readLegacyTransaction() : null);
      if (state && transaction?.state && transaction.state !== state) {
        throw new Error('Login state mismatch - restart sign-in');
      }

      const verifier = transaction?.verifier;
      if (!verifier) throw new Error('PKCE verifier missing - login session expired');

      const body = new URLSearchParams({
        grant_type: 'authorization_code',
        client_id: clientId,
        redirect_uri: redirectUri,
        code,
        code_verifier: verifier,
      });

      const res = await fetch(metadata.token_endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: body.toString(),
      });

      if (!res.ok) {
        const err = await res.text();
        throw new Error(`Token exchange failed: ${err}`);
      }

      const data = await res.json();
      const accessToken = data.access_token;
      const idToken = data.id_token;

      sessionStorage.setItem(TOKEN_KEY, accessToken);
      clearAuthTransaction(state);

      const payload = decodeJwtPayload(idToken || accessToken);
      const user = userFromPayload(payload);
      if (user) {
        sessionStorage.setItem(USER_KEY, JSON.stringify(user));
      }

      notify();
      return { returnPath: safeReturnPath(transaction?.returnPath || DEFAULT_RETURN_PATH) };
    },
  };
}

export function createAuthAdapter() {
  const mockMode = import.meta.env.VITE_MOCK_MODE === 'true';
  const authority = import.meta.env.VITE_OIDC_AUTHORITY || '';
  const discoveryUrl = import.meta.env.VITE_OIDC_DISCOVERY_URL || '';
  const clientId = import.meta.env.VITE_OIDC_CLIENT_ID || '{{OIDC_CLIENT_ID}}';
  const scope = import.meta.env.VITE_OIDC_SCOPE || 'openid profile email';
  const redirectUri = import.meta.env.VITE_OIDC_REDIRECT_URI
    || `${window.location.origin}/auth/callback`;

  if (mockMode) {
    return createMockAdapter();
  }

  if (!authority && !discoveryUrl) {
    throw new Error(
      '[{{APP_SLUG}}] VITE_OIDC_AUTHORITY or VITE_OIDC_DISCOVERY_URL is required. ' +
      'Set one to your OIDC provider, or set VITE_MOCK_MODE=true for local development.',
    );
  }

  return createOidcAdapter({ authority, discoveryUrl, clientId, redirectUri, scope });
}
