// Generated by mozaiks InfraScaffoldAgent — edit after generation as needed.
/**
 * Mock auth adapter for {{APP_SLUG}}.
 *
 * Used when VITE_MOCK_MODE=true or no OIDC provider is configured.
 * Returns a fixed dev user so the app runs without a real identity provider.
 *
 * Template variables substituted at generation time:
 *   {{APP_SLUG}} — app slug used in mock user email
 */

export function createAuthAdapter() {
  const mockUser = {
    id: 'dev-user',
    user_id: 'dev-user',
    email: 'dev@{{APP_SLUG}}.local',
    name: 'Developer',
    firstName: 'Dev',
    lastName: 'User',
    roles: ['admin', 'user'],
  };

  return {
    getCurrentUser: () => Promise.resolve(mockUser),

    onAuthStateChange: (callback) => {
      callback(mockUser);
      return () => {};
    },

    login: () => Promise.resolve(),

    logout: () => {
      window.location.href = '/';
      return Promise.resolve();
    },

    getAccessToken: () => 'dev-token',

    handleCallback: () => Promise.resolve(),
  };
}
