"""Contract tests for the onboarding build context pack.

Verifies that:
- context.yaml registers the pack correctly as config_file capability_source
- context.yaml declares the 3 expected onboarding capabilities
- contract.yaml structure: all required_outputs are generator-owned (no templates dir)
- Forbidden outputs are declared with reasons covering key OSS boundaries:
    WelcomePage.jsx, OnboardingTour components, Spotlight components, shell.json
- Runtime boundaries cover the 6 key constraints:
    tour overlay is OSS, config file as feature flag, step ID consistency,
    href-based selectors, no auth redirect change, user_data_scope
- user_data_scope rule is present (step completion is user-owned PII)
- Cross-pack integrations are documented for mozaikspay and social packs
- No templates/ directory ships (pack is config_file source, not templates source)
- Onboarding step config format is documented in the contract
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

WORKSPACE = Path(__file__).resolve().parents[1]
BUILD_CONTEXT = WORKSPACE / "factory_app" / "build_context"
ONBOARDING = BUILD_CONTEXT / "onboarding"


def _read_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Pack registration
# ---------------------------------------------------------------------------


def test_onboarding_context_registers_active_appgenerator_pack() -> None:
    context = _read_yaml(ONBOARDING / "context.yaml")

    assert context["context_id"] == "onboarding"
    assert "AppGenerator" in context["applies_to_workflows"]
    assert context["pack"]["id"] == "onboarding"
    assert context["pack"]["status"] == "active"


def test_onboarding_context_capability_source_is_config_file() -> None:
    """Onboarding is driven by app/config/onboarding.yaml, not generated module templates."""
    context = _read_yaml(ONBOARDING / "context.yaml")
    assert context["pack"]["capability_source"] == "config_file", (
        "onboarding pack output is a declarative config file and thin state module; "
        "capability_source must be config_file"
    )


def test_onboarding_context_declares_three_capabilities() -> None:
    context = _read_yaml(ONBOARDING / "context.yaml")
    capability_ids = {cap["capability_id"] for cap in (context.get("capabilities") or [])}

    assert capability_ids == {
        "onboarding.tour.show",
        "onboarding.tour.dismiss",
        "onboarding.tour.progress.read",
    }


def test_onboarding_context_capabilities_recommend_user_onboarding_facade() -> None:
    context = _read_yaml(ONBOARDING / "context.yaml")
    for cap in (context.get("capabilities") or []):
        assert cap.get("facade_recommended") == "user_onboarding", (
            f"capability {cap['capability_id']} must recommend user_onboarding facade"
        )


# ---------------------------------------------------------------------------
# Contract structure — generator-owned outputs (no templates)
# ---------------------------------------------------------------------------


def test_onboarding_contract_all_required_outputs_are_generator_owned() -> None:
    """Onboarding has no templates dir — all output is generated by AppGenerator at build time."""
    contract = _read_yaml(ONBOARDING / "contract.yaml")

    template_owned = [
        output["path"]
        for output in contract["required_outputs"]
        if output.get("owner") == "templates"
    ]
    assert template_owned == [], (
        f"onboarding pack has no templates/ — all outputs must be owner: generator or owner: workspace. "
        f"Found template-owned outputs: {template_owned}"
    )


def test_onboarding_contract_required_outputs_include_config_and_module() -> None:
    """Generator must produce onboarding.yaml config and user_onboarding module."""
    contract = _read_yaml(ONBOARDING / "contract.yaml")
    output_paths = {output["path"] for output in contract["required_outputs"]}

    assert "config/onboarding.yaml" in output_paths, (
        "contract.yaml must declare config/onboarding.yaml as a required output"
    )
    assert "modules/user_onboarding/module.yaml" in output_paths, (
        "contract.yaml must declare modules/user_onboarding/module.yaml as a required output"
    )
    assert "modules/user_onboarding/backend/account_data_handler.py" in output_paths, (
        "contract.yaml must declare modules/user_onboarding/backend/account_data_handler.py "
        "because user_onboarding stores user-owned tour state"
    )


def test_onboarding_contract_user_onboarding_module_requires_user_data_scope() -> None:
    """Step completion records are user-owned PII — module.yaml notes must require user_data_scope."""
    contract = _read_yaml(ONBOARDING / "contract.yaml")
    module_output = next(
        (o for o in contract["required_outputs"] if o["path"] == "modules/user_onboarding/module.yaml"),
        None,
    )
    assert module_output is not None
    notes = (module_output.get("notes") or "").lower()
    assert "user_data_scope" in notes, (
        "modules/user_onboarding/module.yaml output notes must require user_data_scope: true — "
        "step completion records are user-owned PII"
    )


# ---------------------------------------------------------------------------
# Forbidden outputs — key OSS boundary rules
# ---------------------------------------------------------------------------


def test_onboarding_contract_forbids_welcome_page() -> None:
    """The tour runs in-place via installTour(); a separate welcome page breaks the intent."""
    contract = _read_yaml(ONBOARDING / "contract.yaml")
    forbidden_paths = {o.get("path") for o in (contract.get("forbidden_outputs") or [])}
    assert "ui/pages/custom/WelcomePage.jsx" in forbidden_paths, (
        "contract.yaml must forbid WelcomePage.jsx — the OSS tour overlay runs in-place"
    )


def test_onboarding_contract_forbids_custom_tour_components() -> None:
    """installTour() is OSS; generated apps must not re-implement the overlay component."""
    contract = _read_yaml(ONBOARDING / "contract.yaml")
    forbidden_prefixes = {o.get("path_prefix") for o in (contract.get("forbidden_outputs") or [])}
    assert "ui/components/OnboardingTour" in forbidden_prefixes, (
        "contract.yaml must forbid ui/components/OnboardingTour* — the OSS runtime provides installTour()"
    )
    assert "ui/components/Spotlight" in forbidden_prefixes, (
        "contract.yaml must forbid ui/components/Spotlight* — the OSS runtime provides the spotlight primitive"
    )


def test_onboarding_contract_forbids_shell_json_modification() -> None:
    """Tour is an overlay, not a navigation destination — shell.json must not be touched."""
    contract = _read_yaml(ONBOARDING / "contract.yaml")
    forbidden_paths = {o.get("path") for o in (contract.get("forbidden_outputs") or [])}
    assert "config/shell.json" in forbidden_paths, (
        "contract.yaml must forbid modifying shell.json — no /welcome route or onboarding nav item"
    )


# ---------------------------------------------------------------------------
# Runtime boundaries
# ---------------------------------------------------------------------------


def test_onboarding_contract_runtime_boundary_tour_overlay_is_oss() -> None:
    boundary_ids = {
        b["id"] for b in (_read_yaml(ONBOARDING / "contract.yaml").get("runtime_boundaries") or [])
    }
    assert "tour_overlay_is_oss" in boundary_ids, (
        "runtime_boundaries must declare tour_overlay_is_oss — "
        "the OSS runtime provides the tour; generated apps must not re-implement it"
    )


def test_onboarding_contract_runtime_boundary_config_is_feature_flag() -> None:
    boundary_ids = {
        b["id"] for b in (_read_yaml(ONBOARDING / "contract.yaml").get("runtime_boundaries") or [])
    }
    assert "config_file_is_the_feature_flag" in boundary_ids, (
        "runtime_boundaries must declare config_file_is_the_feature_flag — "
        "presence of app/config/onboarding.yaml enables the tour; no conditionals or env vars"
    )


def test_onboarding_contract_runtime_boundary_step_id_consistency() -> None:
    boundary_ids = {
        b["id"] for b in (_read_yaml(ONBOARDING / "contract.yaml").get("runtime_boundaries") or [])
    }
    assert "step_ids_must_be_consistent" in boundary_ids, (
        "runtime_boundaries must declare step_ids_must_be_consistent — "
        "step ids in onboarding.yaml must match complete_step enum in module.yaml"
    )


def test_onboarding_contract_runtime_boundary_href_selectors() -> None:
    boundary_ids = {
        b["id"] for b in (_read_yaml(ONBOARDING / "contract.yaml").get("runtime_boundaries") or [])
    }
    assert "selectors_must_be_href_based" in boundary_ids, (
        "runtime_boundaries must declare selectors_must_be_href_based — "
        "Tailwind class selectors are not stable tour targets"
    )


def test_onboarding_contract_runtime_boundary_user_data_scope() -> None:
    contract = _read_yaml(ONBOARDING / "contract.yaml")
    boundary_ids = {b["id"] for b in (contract.get("runtime_boundaries") or [])}
    assert "user_data_scope" in boundary_ids, (
        "runtime_boundaries must declare user_data_scope — "
        "step completion records are user PII requiring account_data_handler.py"
    )


# ---------------------------------------------------------------------------
# Cross-pack integrations
# ---------------------------------------------------------------------------


def test_onboarding_contract_declares_cross_pack_integrations() -> None:
    contract = _read_yaml(ONBOARDING / "contract.yaml")
    integration_pack_ids = {
        i["pack_id"] for i in (contract.get("cross_pack_integrations") or [])
    }
    assert "mozaikspay" in integration_pack_ids, (
        "contract.yaml must document cross-pack integration with mozaikspay — "
        "a billing step should be included when both packs are selected"
    )
    assert "social" in integration_pack_ids, (
        "contract.yaml must document cross-pack integration with social — "
        "a friends/community step should be included when the social pack is present"
    )


# ---------------------------------------------------------------------------
# No templates directory
# ---------------------------------------------------------------------------


def test_onboarding_pack_has_no_templates_directory() -> None:
    """config_file source packs generate output at build time; no pre-built templates ship."""
    templates_dir = ONBOARDING / "templates"
    assert not templates_dir.exists(), (
        "onboarding pack must not ship a templates/ directory — "
        "all output is generator-produced at AppGenerator build time"
    )


def test_onboarding_contract_documents_step_config_format() -> None:
    """The contract must describe the onboarding.yaml step format so the generator can produce valid configs."""
    contract_text = _read_text(ONBOARDING / "contract.yaml")

    assert "selector" in contract_text, (
        "contract.yaml must document the 'selector' field in the step config format"
    )
    assert "step_id" in contract_text or "id:" in contract_text, (
        "contract.yaml must document step id fields"
    )
    assert "placement" in contract_text, (
        "contract.yaml must document placement options (bottom | top | left | right)"
    )
