# DO NOT EDIT — regenerated by AppGenerator from the user_onboarding module contract.
# Override behavior in handler.py, which subclasses this base.
from __future__ import annotations

from typing import Any

from . import service


class UserOnboardingBaseHandler:
    async def get_onboarding_status(
        self, ctx, payload: dict[str, Any]
    ) -> dict[str, Any]:
        user_id = getattr(ctx, "user_id", None) or payload.get("user_id", "")
        return await service.get_onboarding_status(ctx, user_id=user_id)

    async def complete_step(
        self, ctx, payload: dict[str, Any]
    ) -> dict[str, Any]:
        user_id = getattr(ctx, "user_id", None) or payload.get("user_id", "")
        return await service.complete_step(
            ctx,
            user_id=user_id,
            step_id=payload["step_id"],
        )

    async def dismiss_onboarding(
        self, ctx, payload: dict[str, Any]
    ) -> dict[str, Any]:
        user_id = getattr(ctx, "user_id", None) or payload.get("user_id", "")
        return await service.dismiss_onboarding(ctx, user_id=user_id)
