"""{{ACTION_LABEL}} — run via ACA Job, platform cron trigger, or scheduled workflow.

{{ACTION_DESCRIPTION}}

Safe to run frequently (every {{CRON_INTERVAL_MINUTES}} minutes). Emits domain
events and records audit entries. Exits non-zero if any transitions produced
errors so the scheduler can surface failures.

Usage:
    python scripts/{{CRON_SCRIPT_NAME}}.py
    python scripts/{{CRON_SCRIPT_NAME}}.py --mongo-uri mongodb://...

Required env vars:
    MONGO_URI   — MongoDB connection URI

Generated by mozaiks InfraScaffoldAgent. Edit after generation as needed.
Template variables: {{ACTION_LABEL}}, {{ACTION_DESCRIPTION}},
  {{CRON_INTERVAL_MINUTES}}, {{CRON_SCRIPT_NAME}}, {{MODULE_ID}},
  {{SERVICE_CLASS}}, {{TICK_METHOD}}, {{ACTION_ID}}
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.modules.{{MODULE_ID}}.backend.service import {{SERVICE_CLASS}}  # noqa: E402
from mozaiksai.core.core_config import close_mongo_client, get_mongo_client  # noqa: E402


class _MinimalCtx:
    """Minimal context stub for service calls outside the request cycle.

    Captures emitted events without dispatching them to the live event bus.
    Replace with a real dispatcher if downstream reactions must fire during
    the cron tick (uncommon — prefer letting the tick emit events that the
    running app process reacts to via its own subscription).
    """

    def __init__(self) -> None:
        self._emitted: list[tuple[str, dict]] = []

    async def emit(self, event_type: str, payload: dict) -> None:
        self._emitted.append((event_type, payload))


async def run(mongo_uri: str | None = None) -> int:
    if mongo_uri:
        os.environ.setdefault("MONGO_URI", mongo_uri)
    get_mongo_client()  # validates MONGO_URI is present; raises ValueError early if not
    try:
        ctx = _MinimalCtx()
        service = {{SERVICE_CLASS}}()
        result = await service.{{TICK_METHOD}}(ctx)
        errors = result.get("errors", [])
        # Log a compact summary line so container job logs are easy to scan.
        print(f"[{{ACTION_ID}}] result={result} errors={len(errors)}")
        for err in errors:
            print(f"  ERROR: {err}", file=sys.stderr)
        return 1 if errors else 0
    finally:
        close_mongo_client()


def main() -> None:
    parser = argparse.ArgumentParser(description="{{ACTION_LABEL}}")
    parser.add_argument("--mongo-uri", default=None, help="MongoDB connection URI (overrides MONGO_URI env var)")
    args = parser.parse_args()
    sys.exit(asyncio.run(run(mongo_uri=args.mongo_uri)))


if __name__ == "__main__":
    main()
