#!/usr/bin/env bash
# Generated by mozaiks InfraScaffoldAgent — edit after generation as needed.
# ============================================================================
# {{APP_NAME}} — Provision / secret-sync script
# ============================================================================
# What this script does:
#   1. Reads required secret names from app/security/secrets.yaml.
#   2. Validates that all required secrets are present in .env.${ENVIRONMENT}.
#   3. Syncs secrets to GitHub environment secrets via `gh secret set`.
#   4. Syncs secrets to the deploy target ({{DEPLOY_TARGET}}).
#   5. Prints a checklist of remaining manual steps.
#
# Usage:
#   ./scripts/provision.sh [staging|production]   (default: staging)
#
# Prerequisites:
#   - gh CLI: authenticated (`gh auth login`), targeting the correct repo.
#   - python or python3: available on PATH.
#   - For {{DEPLOY_TARGET}}: install and authenticate the platform CLI.
#
# Secrets:
#   Copy .env.${ENVIRONMENT}.example to .env.${ENVIRONMENT} (gitignored) and
#   fill in the provider secret values before running.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SECRETS_YAML="$REPO_ROOT/app/security/secrets.yaml"

ENVIRONMENT="${1:-staging}"
ENV_FILE="$REPO_ROOT/.env.${ENVIRONMENT}"
DRY_RUN=false
[[ "${2:-}" == "--dry-run" ]] && DRY_RUN=true

# ── Helpers ───────────────────────────────────────────────────────────────────

info() { echo "  $*"; }
step() { echo; echo "==> $*"; }
warn() { echo "  [WARN] $*" >&2; }
die()  { echo "  [ERROR] $*" >&2; exit 1; }

# ── Detect Python ─────────────────────────────────────────────────────────────

PYTHON_BIN=""
for candidate in python python3 py; do
  if command -v "$candidate" >/dev/null 2>&1; then
    PYTHON_BIN="$candidate"
    break
  fi
done
[ -n "$PYTHON_BIN" ] || die "python not found on PATH"

# ── Load .env file ────────────────────────────────────────────────────────────

step "Loading $ENV_FILE"
if [ ! -f "$ENV_FILE" ]; then
  die "Secret file not found: $ENV_FILE\nCopy .env.${ENVIRONMENT}.example to .env.${ENVIRONMENT} and fill in values."
fi

set -o allexport
# shellcheck disable=SC1090
source "$ENV_FILE"
set +o allexport
info "Loaded $ENV_FILE"

# ── Read required secret names from secrets.yaml ─────────────────────────────

step "Reading required secrets from app/security/secrets.yaml"
if [ ! -f "$SECRETS_YAML" ]; then
  die "app/security/secrets.yaml not found — cannot determine required secrets"
fi

REQUIRED_NAMES=$("$PYTHON_BIN" - <<'PYEOF'
import sys, yaml
with open(sys.argv[1]) as f:
    doc = yaml.safe_load(f)
names = []
for entry in (doc.get("secrets") or []):
    if entry.get("required", True):
        names.append(entry["name"])
print("\n".join(names))
PYEOF
"$SECRETS_YAML")

# ── Validate all required secrets are present ─────────────────────────────────

step "Validating required secrets"
MISSING=()
for name in $REQUIRED_NAMES; do
  val="${!name:-}"
  if [ -z "$val" ] || [[ "$val" == "placeholder-change-me" ]] || [[ "$val" == "<NEEDED"* ]]; then
    MISSING+=("$name")
  fi
done

if [ ${#MISSING[@]} -gt 0 ]; then
  die "Missing or placeholder required secrets:\n$(printf '  - %s\n' "${MISSING[@]}")\n\nFill these in $ENV_FILE before running provision."
fi
info "All required secrets present"

# ── Sync to GitHub environment secrets ───────────────────────────────────────

step "Syncing to GitHub environment: $ENVIRONMENT"
for name in $REQUIRED_NAMES; do
  val="${!name:-}"
  if [ -n "$val" ]; then
    if $DRY_RUN; then
      info "[dry-run] gh secret set $name --env $ENVIRONMENT"
    else
      echo "$val" | gh secret set "$name" --env "$ENVIRONMENT"
      info "Set GitHub secret: $name"
    fi
  fi
done

# ── Sync to deploy target ────────────────────────────────────────────────────

step "Syncing to deploy target: {{DEPLOY_TARGET}}"
# Replace this block with commands for your deploy target.
#
# Azure Container Apps example:
#   for name in $REQUIRED_NAMES; do
#     val="${!name:-}"
#     if [ -n "$val" ]; then
#       if $DRY_RUN; then
#         info "[dry-run] az containerapp secret set --name {{APP_NAME}} ..."
#       else
#         az containerapp secret set \
#           --name "{{APP_NAME}}" \
#           --resource-group "<rg-name>" \
#           --secrets "${name,,}=$val"
#       fi
#     fi
#   done
#
# Fly.io example:
#   secrets_args=""
#   for name in $REQUIRED_NAMES; do
#     val="${!name:-}"
#     [ -n "$val" ] && secrets_args="$secrets_args ${name}=${val}"
#   done
#   fly secrets set $secrets_args --app {{APP_NAME}}
info "Configure deploy target sync for {{DEPLOY_TARGET}} above"

# ── Checklist ────────────────────────────────────────────────────────────────

step "Remaining manual steps"
cat <<CHECKLIST
  [ ] Verify GitHub environment '$ENVIRONMENT' has all secrets set:
        gh secret list --env $ENVIRONMENT
  [ ] Verify deploy target has all secrets set
  [ ] Trigger a deploy workflow run:
        gh workflow run deploy.yml --ref main -f environment=$ENVIRONMENT
  [ ] Watch the run:
        gh run watch
CHECKLIST

echo
info "Provision complete."
