"""Shared transport and configuration for MozaiksCloud sub-clients.

This module provides base connectivity for the Mozaiks Cloud managed connector.
Generated apps must not import Azure, Cloudflare, or GitHub SDKs directly.
All cloud operations route through the bounded sub-clients (deployment,
environment, domain) that use this transport.

This file is generated by the mozaiks_cloud capability pack and copied to:
    services/integrations/mozaiks_cloud_client.py
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any

import httpx

_DEFAULT_TIMEOUT = 20.0
_DEFAULT_MAX_RETRIES = 3
_CONNECTOR_SERVICE = "mozaiks_cloud"
_PROVIDER_API_PREFIX = "/api/mozaiks-cloud/v1"
_API_VERSION = "v1"


class MozaiksCloudError(Exception):
    """Base exception for MozaiksCloud client errors."""


class MozaiksCloudConfigurationError(MozaiksCloudError):
    """Raised when Mozaiks Cloud provider config is unavailable."""


class MozaiksCloudHTTPError(MozaiksCloudError):
    """Raised when the platform returns a non-2xx HTTP status."""

    def __init__(self, status_code: int, detail: str = "", error_kind: str = "unknown") -> None:
        self.status_code = status_code
        self.error_kind = error_kind
        super().__init__(f"HTTP {status_code} [{error_kind}]: {detail}")


class MozaiksCloudApplicationError(MozaiksCloudError):
    """Raised when the platform returns an application-level error."""

    def __init__(self, error: str, error_kind: str = "unknown") -> None:
        self.error = error
        self.error_kind = error_kind
        super().__init__(error)


@dataclass(frozen=True)
class MozaiksCloudConnectorSettings:
    api_base: str | None = None
    api_key: str | None = None
    app_id: str | None = None
    source: str = "unconfigured"

    @property
    def has_credentials(self) -> bool:
        return bool(self.api_base and self.api_key)


def _clean(value: Any) -> str:
    return str(value or "").strip()


def _env_settings() -> MozaiksCloudConnectorSettings:
    return MozaiksCloudConnectorSettings(
        api_base=_clean(os.getenv("MOZAIKS_CLOUD_API_BASE")) or None,
        api_key=_clean(os.getenv("MOZAIKS_CLOUD_API_KEY")) or None,
        app_id=_clean(os.getenv("MOZAIKS_CLOUD_APP_ID")) or None,
        source="env",
    )


async def _load_connector_settings(app_id: str | None) -> MozaiksCloudConnectorSettings | None:
    """Load app-scoped Mozaiks Cloud connector config when Studio stored it.

    The connector record stores only frontend-safe config. The API key is
    fetched from the configured connector vault. Missing or unavailable vault
    state falls back to environment variables in the caller.
    """
    if not app_id:
        return None
    try:
        from mozaiksai.core.data.persistence.connector_store import ConnectorStore
        from mozaiksai.core.secrets import get_connector_vault_backend

        record = await ConnectorStore().get(
            scope=ConnectorStore.SCOPE_APP,
            scope_id=str(app_id),
            service=_CONNECTOR_SERVICE,
        )
        if not isinstance(record, dict):
            return None
        raw_public_config = record.get("public_config")
        public_config: dict[str, Any] = (
            raw_public_config if isinstance(raw_public_config, dict) else {}
        )
        secret_result = await get_connector_vault_backend().get_secret(
            scope_id=str(app_id),
            service=_CONNECTOR_SERVICE,
        )
        credential = (
            _clean(secret_result.get("secret_value"))
            if isinstance(secret_result, dict)
            else ""
        )
        api_base = _clean(public_config.get("api_base")) or None
        cloud_app_id = _clean(public_config.get("app_id")) or None
        if not api_base and not credential:
            return None
        return MozaiksCloudConnectorSettings(
            api_base=api_base,
            api_key=credential or None,
            app_id=cloud_app_id,
            source="connector",
        )
    except Exception:
        return None


def _authorization_header(value: str) -> str:
    return value if value.lower().startswith(("bearer ", "basic ")) else f"Bearer {value}"


def _classify_error_kind(status_code: int, body: dict[str, Any]) -> str:
    if kind := body.get("error_kind"):
        return str(kind)
    if status_code in (401, 403):
        return "auth_error"
    if status_code == 404:
        return "not_found"
    if status_code == 409:
        return "conflict"
    if status_code == 422:
        return "validation_error"
    if status_code == 429:
        return "rate_limited"
    if status_code >= 500:
        return "provider_error"
    return "unknown"


class MozaiksCloudTransport:
    """Shared HTTP transport and credential resolution for MozaiksCloud sub-clients.

    Sub-clients instantiate this transport and call request() for each operation.
    This class is not used directly by generated app modules — use the bounded
    sub-clients (MozaiksCloudDeploymentClient, MozaiksCloudEnvironmentClient,
    MozaiksCloudDomainClient) instead.

    Retries are bounded by max_retries (default 3, capped at 5). Only 5xx
    responses and transient network errors are retried; client errors (4xx)
    are not.

    All requests include Idempotency-Key when provided, and the
    X-MozaiksCloud-Api-Version header for provider API version negotiation.
    """

    def __init__(
        self,
        api_base: str | None = None,
        api_key: str | None = None,
        app_id: str | None = None,
        timeout_seconds: float = _DEFAULT_TIMEOUT,
        max_retries: int = _DEFAULT_MAX_RETRIES,
        connector_settings_loader: Any = None,
    ) -> None:
        self._api_base = _clean(api_base) or None
        self._api_key = _clean(api_key) or None
        self._app_id = _clean(app_id) or None
        self._timeout = timeout_seconds
        self._max_retries = max(1, min(max_retries, 5))
        self._connector_settings_loader = connector_settings_loader or _load_connector_settings
        self._settings_cache: MozaiksCloudConnectorSettings | None = None

    async def settings(self) -> MozaiksCloudConnectorSettings:
        if self._settings_cache is not None:
            return self._settings_cache

        connector = await self._connector_settings_loader(self._app_id)
        env = _env_settings()
        resolved = MozaiksCloudConnectorSettings(
            api_base=(
                self._api_base
                or (connector.api_base if connector else None)
                or env.api_base
            ),
            api_key=(
                self._api_key
                or (connector.api_key if connector else None)
                or env.api_key
            ),
            app_id=(
                self._app_id
                or (connector.app_id if connector else None)
                or env.app_id
            ),
            source=(
                "explicit"
                if (self._api_base or self._api_key)
                else (connector.source if connector else env.source)
            ),
        )
        if not resolved.api_base:
            raise MozaiksCloudConfigurationError(
                "Mozaiks Cloud is not configured. Add the mozaiks_cloud connector "
                "or set MOZAIKS_CLOUD_API_BASE."
            )
        if not resolved.api_key:
            raise MozaiksCloudConfigurationError(
                "Mozaiks Cloud API key is required. Set MOZAIKS_CLOUD_API_KEY or "
                "configure the mozaiks_cloud connector with an api_key."
            )
        self._settings_cache = resolved
        return resolved

    async def request(
        self,
        method: str,
        path: str,
        *,
        json: dict[str, Any] | None = None,
        params: dict[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> dict[str, Any]:
        cfg = await self.settings()
        base = cfg.api_base.rstrip("/") if cfg.api_base else ""
        url = f"{base}{_PROVIDER_API_PREFIX}{path}"
        headers: dict[str, str] = {
            "Content-Type": "application/json",
            "X-MozaiksCloud-Api-Version": _API_VERSION,
        }
        if cfg.api_key:
            headers["Authorization"] = _authorization_header(cfg.api_key)
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key

        last_exc: Exception | None = None
        attempts = 0
        while attempts < self._max_retries:
            attempts += 1
            try:
                async with httpx.AsyncClient(timeout=self._timeout) as client:
                    response = await client.request(
                        method, url, json=json, params=params, headers=headers
                    )
            except httpx.TimeoutException as exc:
                last_exc = MozaiksCloudHTTPError(0, f"Request timed out: {exc}", "timeout")
                if attempts >= self._max_retries:
                    raise last_exc from exc
                continue
            except httpx.RequestError as exc:
                last_exc = MozaiksCloudHTTPError(0, f"Network error: {exc}", "provider_error")
                if attempts >= self._max_retries:
                    raise last_exc from exc
                continue

            if response.is_success:
                try:
                    data: dict[str, Any] = response.json()
                except Exception as exc:
                    raise MozaiksCloudHTTPError(
                        response.status_code, "Non-JSON response body", "provider_error"
                    ) from exc
                if data.get("success") is False and "error" in data:
                    raise MozaiksCloudApplicationError(
                        str(data["error"]),
                        str(data.get("error_kind", "unknown")),
                    )
                return data

            body: dict[str, Any] = {}
            try:
                body = response.json()
            except Exception:
                pass
            error_kind = _classify_error_kind(response.status_code, body)
            detail = body.get("detail") or body.get("error") or response.text[:200]
            if response.status_code >= 500 and attempts < self._max_retries:
                last_exc = MozaiksCloudHTTPError(response.status_code, detail, error_kind)
                continue
            raise MozaiksCloudHTTPError(response.status_code, detail, error_kind)

        if last_exc is not None:
            raise last_exc
        raise MozaiksCloudHTTPError(0, "Exhausted retries", "provider_error")

    async def health(self, path: str = "/health") -> dict[str, Any]:
        """Health/readiness probe — does not require pre-validated credentials."""
        try:
            cfg = await self.settings()
        except MozaiksCloudConfigurationError as exc:
            return {"status": "unconfigured", "error": str(exc)}
        base = cfg.api_base.rstrip("/") if cfg.api_base else ""
        url = f"{base}{_PROVIDER_API_PREFIX}{path}"
        headers: dict[str, str] = {"X-MozaiksCloud-Api-Version": _API_VERSION}
        if cfg.api_key:
            headers["Authorization"] = _authorization_header(cfg.api_key)
        try:
            async with httpx.AsyncClient(timeout=self._timeout) as client:
                response = await client.get(url, headers=headers)
            if response.is_success:
                return dict(response.json())
            return {"status": "unhealthy", "http_status": response.status_code}
        except Exception as exc:
            return {"status": "unreachable", "error": str(exc)}
