"""MozaiksCloud deployment client for generated apps.

Handles deployment submission, status retrieval, and rollback operations
through the Mozaiks Cloud managed deployment platform.

This file is generated by the mozaiks_cloud capability pack and copied to:
    services/integrations/mozaiks_cloud_deployment_client.py

Generated apps must not import Azure SDK, Cloudflare SDK, or GitHub SDK directly.
All deployment operations route through this bounded client.

Status values (closed set — do not branch on values outside this set):
  pending | running | succeeded | failed | cancelled | rolling_back
"""

from __future__ import annotations

from typing import Any

from .mozaiks_cloud_client import MozaiksCloudTransport


class MozaiksCloudDeploymentClient:
    """Bounded client for Mozaiks Cloud deployment operations.

    Bounded operations:
    - submit_deployment_request: submit an authorized deployment
    - get_deployment_status: retrieve normalized operation status
    - request_rollback: request rollback through an authorized operation
    - health: deployment service health/readiness

    Each mutating operation requires a caller-supplied idempotency_key.
    Retries with the same key are safe — the provider deduplicates them.
    """

    def __init__(self, transport: MozaiksCloudTransport) -> None:
        self._transport = transport

    async def submit_deployment_request(
        self,
        *,
        app_id: str,
        environment: str,
        release_ref: str,
        idempotency_key: str,
    ) -> dict[str, Any]:
        """Submit an authorized deployment/release request.

        Returns a normalized response with operation_id, status, environment,
        release_ref, and created_at. Use get_deployment_status to poll progress.
        Status values: pending, running, succeeded, failed, cancelled, rolling_back.
        """
        return await self._transport.request(
            "POST",
            "/deployments",
            json={
                "app_id": app_id,
                "environment": environment,
                "release_ref": release_ref,
                "idempotency_key": idempotency_key,
            },
            idempotency_key=idempotency_key,
        )

    async def get_deployment_status(self, *, operation_id: str) -> dict[str, Any]:
        """Retrieve normalized deployment operation status.

        Returns operation_id, status, environment, release_ref, created_at, updated_at.
        """
        return await self._transport.request(
            "GET",
            f"/deployments/{operation_id}",
        )

    async def request_rollback(
        self,
        *,
        operation_id: str,
        target_release_ref: str,
        idempotency_key: str,
    ) -> dict[str, Any]:
        """Request rollback through an explicitly authorized operation.

        Returns a normalized response for the rollback request with a new
        operation_id tracking the rollback. The original operation_id identifies
        the deployment being rolled back.
        """
        return await self._transport.request(
            "POST",
            f"/deployments/{operation_id}/rollback",
            json={
                "target_release_ref": target_release_ref,
                "idempotency_key": idempotency_key,
            },
            idempotency_key=idempotency_key,
        )

    async def health(self) -> dict[str, Any]:
        """Deployment service health/readiness probe."""
        return await self._transport.health("/health")
