"""MozaiksCloud environment client for generated apps.

Retrieves normalized environment endpoints from the Mozaiks Cloud platform.

This file is generated by the mozaiks_cloud capability pack and copied to:
    services/integrations/mozaiks_cloud_environment_client.py

Returned endpoints contain only normalized url, kind, and region fields.
Provider-internal resource IDs (azure_resource_id, cloudflare_zone_id, etc.)
are never included in environment endpoint responses.
"""

from __future__ import annotations

from typing import Any

from .mozaiks_cloud_client import MozaiksCloudTransport


class MozaiksCloudEnvironmentClient:
    """Bounded client for Mozaiks Cloud environment operations.

    Bounded operations:
    - get_environment_endpoints: retrieve normalized environment endpoints

    Environment endpoint shape (per endpoint in the list):
      url: str       — publicly accessible base URL for this environment
      kind: str      — endpoint category (e.g., 'primary', 'preview', 'admin')
      region: str | null — optional normalized region name
    """

    def __init__(self, transport: MozaiksCloudTransport) -> None:
        self._transport = transport

    async def get_environment_endpoints(
        self,
        *,
        app_id: str,
        environment: str,
    ) -> dict[str, Any]:
        """Retrieve normalized environment endpoints.

        Returns environment name and a list of endpoint objects, each with
        url, kind, and optional region. Generated apps display these endpoints;
        they must not store or forward internal provider resource IDs.
        """
        return await self._transport.request(
            "GET",
            f"/environments/{app_id}/{environment}/endpoints",
        )
