"""MozaiksCloud domain client for generated apps.

Manages domain connections, verification, DNS instructions, activation,
status retrieval, and disconnection through the Mozaiks Cloud domain platform.

This file is generated by the mozaiks_cloud capability pack and copied to:
    services/integrations/mozaiks_cloud_domain_client.py

Generated apps must not import Cloudflare SDK, boto3, or any direct DNS/TLS
provider SDK. All domain operations route through this bounded client.

Domain status values (closed set):
  pending_verification | verified | activating | active | failed | disconnected

TLS status values (closed set):
  pending | provisioning | active | failed
"""

from __future__ import annotations

from typing import Any

from .mozaiks_cloud_client import MozaiksCloudTransport


class MozaiksCloudDomainClient:
    """Bounded client for Mozaiks Cloud domain management operations.

    Bounded operations:
    - connect_domain: connect an existing domain
    - get_domain_verification: request ownership verification status
    - get_dns_instructions: retrieve DNS configuration instructions
    - request_domain_activation: activate after verification
    - get_domain_status: retrieve DNS and TLS status
    - disconnect_domain: disconnect a domain
    - health: domain service health/readiness

    Each mutating operation requires a caller-supplied idempotency_key.
    Retries with the same key are safe — the provider deduplicates them.
    DNS records returned by this client are for display only. Generated apps
    must not apply DNS changes directly; the Mozaiks Cloud provider applies them.
    """

    def __init__(self, transport: MozaiksCloudTransport) -> None:
        self._transport = transport

    async def connect_domain(
        self,
        *,
        app_id: str,
        domain: str,
        idempotency_key: str,
    ) -> dict[str, Any]:
        """Connect an existing domain to the app.

        Returns a normalized response with operation_id, status, domain, and
        created_at. Status starts at pending_verification.
        """
        return await self._transport.request(
            "POST",
            "/domains",
            json={
                "app_id": app_id,
                "domain": domain,
                "idempotency_key": idempotency_key,
            },
            idempotency_key=idempotency_key,
        )

    async def get_domain_verification(self, *, operation_id: str) -> dict[str, Any]:
        """Request ownership verification status and instructions.

        Returns operation_id, domain, status, and verification_records.
        Each record has type, name, value, and optional ttl.
        """
        return await self._transport.request(
            "GET",
            f"/domains/{operation_id}/verification",
        )

    async def get_dns_instructions(self, *, operation_id: str) -> dict[str, Any]:
        """Retrieve DNS configuration instructions.

        Returns domain and records (list of DnsRecord).
        Each record has type, name, value, and optional ttl.
        Generated apps display these instructions; they must not apply
        DNS changes directly.
        """
        return await self._transport.request(
            "GET",
            f"/domains/{operation_id}/dns-instructions",
        )

    async def request_domain_activation(
        self,
        *,
        operation_id: str,
        idempotency_key: str,
    ) -> dict[str, Any]:
        """Request domain activation after ownership verification.

        Returns a normalized response with operation_id, status, domain,
        and created_at. Status transitions to activating then active.
        """
        return await self._transport.request(
            "POST",
            f"/domains/{operation_id}/activate",
            json={"idempotency_key": idempotency_key},
            idempotency_key=idempotency_key,
        )

    async def get_domain_status(self, *, domain: str) -> dict[str, Any]:
        """Retrieve DNS and TLS status for a connected domain.

        Returns domain, status, dns_verified (bool), tls_status, created_at,
        updated_at.
        Domain status: pending_verification | verified | activating | active | failed | disconnected
        TLS status: pending | provisioning | active | failed
        """
        return await self._transport.request(
            "GET",
            f"/domains/by-name/{domain}/status",
        )

    async def disconnect_domain(
        self,
        *,
        domain: str,
        idempotency_key: str,
    ) -> dict[str, Any]:
        """Disconnect a domain from the app.

        Returns domain and status ('disconnected').
        """
        return await self._transport.request(
            "DELETE",
            f"/domains/by-name/{domain}",
            json={"idempotency_key": idempotency_key},
            idempotency_key=idempotency_key,
        )

    async def health(self) -> dict[str, Any]:
        """Domain service health/readiness probe."""
        return await self._transport.health("/domains/health")
