# DO NOT EDIT — regenerated by AppGenerator from the notification_settings module contract.
# Override behavior in handler.py, which subclasses this base.
from __future__ import annotations

from typing import Any

from . import service


class NotificationSettingsBaseHandler:
    async def get_notification_preferences(
        self, ctx, payload: dict[str, Any]
    ) -> dict[str, Any]:
        user_id = getattr(ctx, "user_id", None) or payload.get("user_id", "")
        return await service.get_notification_preferences(ctx, user_id=user_id)

    async def update_notification_preferences(
        self, ctx, payload: dict[str, Any]
    ) -> dict[str, Any]:
        user_id = getattr(ctx, "user_id", None) or payload.get("user_id", "")
        return await service.update_notification_preferences(
            ctx,
            user_id=user_id,
            email_enabled=payload.get("email_enabled"),
            push_enabled=payload.get("push_enabled"),
            sms_enabled=payload.get("sms_enabled"),
        )
